function setValuesOLSRpreset(preset)
{
    if(preset=="fixed")
    {
        $("#HelloInterval").val("5.0");
        $("#HelloValidityTime").val("100.0");
        $("#TcInterval").val("5.0");
        $("#TcValidityTime").val("100.0");
        $("#HnaInterval").val("5.0");
        $("#HnaValidityTime").val("200.0");
    }
    if(preset=="mobile")
    {
        $("#HelloInterval").val("1.0");
        $("#HelloValidityTime").val("20.0");
        $("#TcInterval").val("1.0");
        $("#TcValidityTime").val("20.0");
        $("#HnaInterval").val("2.0");
        $("#HnaValidityTime").val("50.0");
    }
}