#!/bin/bash
# /bin/sensorParser.sh

remountrw
java -jar /bin/sensorParser.jar &


#!/bin/bash
# /bin/sensorParserD.sh

    case "$1" in
      start)
            if [ -f /var/lock/sensorParser ]
            then
               exit 1
            else
                touch /var/lock/sensorParser
                /bin/sensorParser.sh &
            fi
            ;;
      stop)
            rm  /var/lock/sensorParser
            /usr/bin/killall sensorParser.sh
            PID=`ps aux | grep "[s]ensorParser.jar" | awk '{ print $2 }'`
            kill $PID
            ;;
      *)
            echo "Uso: $0 start|stop" >&2
            exit 3
            ;;
    esac
    exit 0
